<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MedicationsInventorySeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'medication_id' => 'MED-001',
                'medication_name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'strength' => '500mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 150,
                'minimum_stock' => 50,
                'maximum_stock' => 200,
                'unit_price' => 2.50,
                'category' => 'Analgesic',
                'supplier' => 'Unilab Philippines',
                'location' => 'Shelf A1',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => false,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-002',
                'medication_name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'strength' => '400mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 120,
                'minimum_stock' => 30,
                'maximum_stock' => 150,
                'unit_price' => 3.00,
                'category' => 'NSAID',
                'supplier' => 'Unilab Philippines',
                'location' => 'Shelf A2',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => false,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-003',
                'medication_name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'strength' => '250mg',
                'dosage_form' => 'Capsule',
                'current_stock' => 80,
                'minimum_stock' => 30,
                'maximum_stock' => 100,
                'unit_price' => 15.00,
                'category' => 'Antibiotic',
                'supplier' => 'Pfizer Philippines',
                'location' => 'Shelf B2',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-004',
                'medication_name' => 'Lisinopril',
                'generic_name' => 'Lisinopril',
                'strength' => '10mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 60,
                'minimum_stock' => 25,
                'maximum_stock' => 80,
                'unit_price' => 8.50,
                'category' => 'ACE Inhibitor',
                'supplier' => 'Merck Philippines',
                'location' => 'Shelf C1',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-005',
                'medication_name' => 'Metformin',
                'generic_name' => 'Metformin',
                'strength' => '500mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 100,
                'minimum_stock' => 40,
                'maximum_stock' => 120,
                'unit_price' => 5.00,
                'category' => 'Antidiabetic',
                'supplier' => 'Merck Philippines',
                'location' => 'Shelf C3',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-006',
                'medication_name' => 'Atorvastatin',
                'generic_name' => 'Atorvastatin',
                'strength' => '20mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 70,
                'minimum_stock' => 30,
                'maximum_stock' => 90,
                'unit_price' => 12.00,
                'category' => 'Statin',
                'supplier' => 'Pfizer Philippines',
                'location' => 'Shelf C2',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-007',
                'medication_name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'strength' => '20mg',
                'dosage_form' => 'Capsule',
                'current_stock' => 90,
                'minimum_stock' => 25,
                'maximum_stock' => 110,
                'unit_price' => 18.00,
                'category' => 'Proton Pump Inhibitor',
                'supplier' => 'AstraZeneca Philippines',
                'location' => 'Shelf D2',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-008',
                'medication_name' => 'Amlodipine',
                'generic_name' => 'Amlodipine',
                'strength' => '5mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 85,
                'minimum_stock' => 30,
                'maximum_stock' => 100,
                'unit_price' => 7.50,
                'category' => 'Calcium Channel Blocker',
                'supplier' => 'Pfizer Philippines',
                'location' => 'Shelf D1',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-009',
                'medication_name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic Acid',
                'strength' => '100mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 200,
                'minimum_stock' => 25,
                'maximum_stock' => 250,
                'unit_price' => 1.50,
                'category' => 'Antiplatelet',
                'supplier' => 'Bayer Philippines',
                'location' => 'Shelf A3',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => false,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-010',
                'medication_name' => 'Simvastatin',
                'generic_name' => 'Simvastatin',
                'strength' => '40mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 65,
                'minimum_stock' => 20,
                'maximum_stock' => 80,
                'unit_price' => 10.00,
                'category' => 'Statin',
                'supplier' => 'Merck Philippines',
                'location' => 'Shelf C4',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-011',
                'medication_name' => 'Losartan',
                'generic_name' => 'Losartan',
                'strength' => '50mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 55,
                'minimum_stock' => 25,
                'maximum_stock' => 70,
                'unit_price' => 9.00,
                'category' => 'ARB',
                'supplier' => 'Merck Philippines',
                'location' => 'Shelf D3',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-012',
                'medication_name' => 'Metoprolol',
                'generic_name' => 'Metoprolol',
                'strength' => '50mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 75,
                'minimum_stock' => 30,
                'maximum_stock' => 90,
                'unit_price' => 6.50,
                'category' => 'Beta Blocker',
                'supplier' => 'AstraZeneca Philippines',
                'location' => 'Shelf D4',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-013',
                'medication_name' => 'Furosemide',
                'generic_name' => 'Furosemide',
                'strength' => '40mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 60,
                'minimum_stock' => 30,
                'maximum_stock' => 80,
                'unit_price' => 4.00,
                'category' => 'Diuretic',
                'supplier' => 'Sanofi Philippines',
                'location' => 'Shelf B3',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-014',
                'medication_name' => 'Warfarin',
                'generic_name' => 'Warfarin',
                'strength' => '5mg',
                'dosage_form' => 'Tablet',
                'current_stock' => 40,
                'minimum_stock' => 20,
                'maximum_stock' => 60,
                'unit_price' => 3.50,
                'category' => 'Anticoagulant',
                'supplier' => 'Bristol-Myers Squibb',
                'location' => 'Shelf B4',
                'storage_conditions' => 'Room Temperature',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-015',
                'medication_name' => 'Insulin Regular',
                'generic_name' => 'Insulin Human',
                'strength' => '100U/ml',
                'dosage_form' => 'Injection',
                'current_stock' => 50,
                'minimum_stock' => 20,
                'maximum_stock' => 80,
                'unit_price' => 150.00,
                'category' => 'Insulin',
                'supplier' => 'Eli Lilly Philippines',
                'location' => 'Refrigerator A2',
                'storage_conditions' => 'Refrigerated',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'medication_id' => 'MED-016',
                'medication_name' => 'Insulin Glargine',
                'generic_name' => 'Insulin Glargine',
                'strength' => '100U/ml',
                'dosage_form' => 'Injection',
                'current_stock' => 35,
                'minimum_stock' => 15,
                'maximum_stock' => 60,
                'unit_price' => 200.00,
                'category' => 'Insulin',
                'supplier' => 'Sanofi Philippines',
                'location' => 'Refrigerator A1',
                'storage_conditions' => 'Refrigerated',
                'requires_prescription' => true,
                'status' => 'Active',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ]
        ];

        $this->db->table('medications_inventory')->insertBatch($data);
    }
}
