<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class StockAlertsSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // Original 6 medications with alerts
            [
                'alert_id' => 'ALT-2024-001',
                'medication_name' => 'Amoxicillin 250mg',
                'alert_type' => 'Low Stock',
                'priority' => 'High',
                'status' => 'Active',
                'current_stock' => 15,
                'minimum_required' => 30,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf B2',
                'supplier' => 'Pfizer Philippines',
                'description' => 'Stock level below minimum threshold',
                'created_at' => '2024-01-15 10:30:00',
                'updated_at' => '2024-01-15 10:30:00'
            ],
            [
                'alert_id' => 'ALT-2024-002',
                'medication_name' => 'Insulin Glargine 100U/ml',
                'alert_type' => 'Expiring Soon',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 8,
                'minimum_required' => null,
                'expiry_date' => '2024-02-20',
                'days_remaining' => 36,
                'batch_number' => 'INS240201',
                'location' => 'Refrigerator A1',
                'supplier' => 'Sanofi Philippines',
                'description' => 'Medication expiring within 60 days',
                'created_at' => '2024-01-15 09:15:00',
                'updated_at' => '2024-01-15 09:15:00'
            ],
            [
                'alert_id' => 'ALT-2024-003',
                'medication_name' => 'Paracetamol 500mg',
                'alert_type' => 'Out of Stock',
                'priority' => 'Critical',
                'status' => 'Active',
                'current_stock' => 0,
                'minimum_required' => 50,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf A1',
                'supplier' => 'Unilab Philippines',
                'description' => 'Complete stock depletion',
                'created_at' => '2024-01-15 08:45:00',
                'updated_at' => '2024-01-15 08:45:00'
            ],
            [
                'alert_id' => 'ALT-2024-004',
                'medication_name' => 'Metformin 500mg',
                'alert_type' => 'Low Stock',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 25,
                'minimum_required' => 40,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf C3',
                'supplier' => 'Merck Philippines',
                'description' => 'Stock approaching minimum threshold',
                'created_at' => '2024-01-15 11:20:00',
                'updated_at' => '2024-01-15 11:20:00'
            ],
            [
                'alert_id' => 'ALT-2024-005',
                'medication_name' => 'Omeprazole 20mg',
                'alert_type' => 'Expired',
                'priority' => 'Critical',
                'status' => 'Active',
                'current_stock' => 12,
                'minimum_required' => null,
                'expiry_date' => '2024-01-10',
                'days_remaining' => -5,
                'batch_number' => 'OME240101',
                'location' => 'Shelf D2',
                'supplier' => 'AstraZeneca Philippines',
                'description' => 'Medication has expired and must be removed',
                'created_at' => '2024-01-15 07:30:00',
                'updated_at' => '2024-01-15 07:30:00'
            ],
            [
                'alert_id' => 'ALT-2024-006',
                'medication_name' => 'Ibuprofen 400mg',
                'alert_type' => 'Low Stock',
                'priority' => 'Low',
                'status' => 'Active',
                'current_stock' => 35,
                'minimum_required' => 30,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf A2',
                'supplier' => 'Unilab Philippines',
                'description' => 'Stock slightly below optimal level',
                'created_at' => '2024-01-15 12:15:00',
                'updated_at' => '2024-01-15 12:15:00'
            ],
            
            // Additional medications from your list
            [
                'alert_id' => 'ALT-2024-007',
                'medication_name' => 'Lisinopril 10mg',
                'alert_type' => 'Low Stock',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 18,
                'minimum_required' => 25,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf C1',
                'supplier' => 'Merck Philippines',
                'description' => 'Stock level below minimum threshold',
                'created_at' => '2024-01-15 13:00:00',
                'updated_at' => '2024-01-15 13:00:00'
            ],
            [
                'alert_id' => 'ALT-2024-008',
                'medication_name' => 'Atorvastatin 20mg',
                'alert_type' => 'Low Stock',
                'priority' => 'High',
                'status' => 'Active',
                'current_stock' => 12,
                'minimum_required' => 30,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf C2',
                'supplier' => 'Pfizer Philippines',
                'description' => 'Stock level below minimum threshold',
                'created_at' => '2024-01-15 13:15:00',
                'updated_at' => '2024-01-15 13:15:00'
            ],
            [
                'alert_id' => 'ALT-2024-009',
                'medication_name' => 'Amlodipine 5mg',
                'alert_type' => 'Expiring Soon',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 22,
                'minimum_required' => null,
                'expiry_date' => '2024-03-15',
                'days_remaining' => 59,
                'batch_number' => 'AML240301',
                'location' => 'Shelf D1',
                'supplier' => 'Pfizer Philippines',
                'description' => 'Medication expiring within 60 days',
                'created_at' => '2024-01-15 13:30:00',
                'updated_at' => '2024-01-15 13:30:00'
            ],
            [
                'alert_id' => 'ALT-2024-010',
                'medication_name' => 'Aspirin 100mg',
                'alert_type' => 'Low Stock',
                'priority' => 'Low',
                'status' => 'Active',
                'current_stock' => 28,
                'minimum_required' => 25,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf A3',
                'supplier' => 'Bayer Philippines',
                'description' => 'Stock slightly below optimal level',
                'created_at' => '2024-01-15 13:45:00',
                'updated_at' => '2024-01-15 13:45:00'
            ],
            [
                'alert_id' => 'ALT-2024-011',
                'medication_name' => 'Simvastatin 40mg',
                'alert_type' => 'Low Stock',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 16,
                'minimum_required' => 20,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf C4',
                'supplier' => 'Merck Philippines',
                'description' => 'Stock approaching minimum threshold',
                'created_at' => '2024-01-15 14:00:00',
                'updated_at' => '2024-01-15 14:00:00'
            ],
            [
                'alert_id' => 'ALT-2024-012',
                'medication_name' => 'Losartan 50mg',
                'alert_type' => 'Low Stock',
                'priority' => 'High',
                'status' => 'Active',
                'current_stock' => 8,
                'minimum_required' => 25,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf D3',
                'supplier' => 'Merck Philippines',
                'description' => 'Stock level below minimum threshold',
                'created_at' => '2024-01-15 14:15:00',
                'updated_at' => '2024-01-15 14:15:00'
            ],
            [
                'alert_id' => 'ALT-2024-013',
                'medication_name' => 'Metoprolol 50mg',
                'alert_type' => 'Expiring Soon',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 14,
                'minimum_required' => null,
                'expiry_date' => '2024-02-28',
                'days_remaining' => 44,
                'batch_number' => 'MET240228',
                'location' => 'Shelf D4',
                'supplier' => 'AstraZeneca Philippines',
                'description' => 'Medication expiring within 60 days',
                'created_at' => '2024-01-15 14:30:00',
                'updated_at' => '2024-01-15 14:30:00'
            ],
            [
                'alert_id' => 'ALT-2024-014',
                'medication_name' => 'Furosemide 40mg',
                'alert_type' => 'Low Stock',
                'priority' => 'Medium',
                'status' => 'Active',
                'current_stock' => 20,
                'minimum_required' => 30,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Shelf B3',
                'supplier' => 'Sanofi Philippines',
                'description' => 'Stock approaching minimum threshold',
                'created_at' => '2024-01-15 14:45:00',
                'updated_at' => '2024-01-15 14:45:00'
            ],
            [
                'alert_id' => 'ALT-2024-015',
                'medication_name' => 'Warfarin 5mg',
                'alert_type' => 'Expired',
                'priority' => 'Critical',
                'status' => 'Active',
                'current_stock' => 6,
                'minimum_required' => null,
                'expiry_date' => '2024-01-05',
                'days_remaining' => -10,
                'batch_number' => 'WAR240105',
                'location' => 'Shelf B4',
                'supplier' => 'Bristol-Myers Squibb',
                'description' => 'Medication has expired and must be removed',
                'created_at' => '2024-01-15 15:00:00',
                'updated_at' => '2024-01-15 15:00:00'
            ],
            [
                'alert_id' => 'ALT-2024-016',
                'medication_name' => 'Insulin Regular 100U/ml',
                'alert_type' => 'Low Stock',
                'priority' => 'High',
                'status' => 'Active',
                'current_stock' => 10,
                'minimum_required' => 20,
                'expiry_date' => null,
                'days_remaining' => null,
                'batch_number' => null,
                'location' => 'Refrigerator A2',
                'supplier' => 'Eli Lilly Philippines',
                'description' => 'Stock level below minimum threshold',
                'created_at' => '2024-01-15 15:15:00',
                'updated_at' => '2024-01-15 15:15:00'
            ]
        ];

        $this->db->table('stock_alerts')->insertBatch($data);
    }
}
